[package]
name = "ntap"
version = "0.10.0"
edition = "2024"
authors = ["shellrow <shellrow@foctal.com>"]
description = "Network traffic monitor/analyzer"
repository = "https://github.com/shellrow/ntap"
homepage = "https://github.com/shellrow/ntap"
documentation = "https://github.com/shellrow/ntap"
readme = "README.md"
keywords = ["network","security","cross-platform"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
anyhow = "1.0.104"
bytes = "1.12.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["time", "chrono"] }
netdev = { version = "0.46.0", features = ["serde"] }
nex = { version = "0.27.0", features = ["serde"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "time"] }
clap = { version = "4.6.6", features = ["cargo", "derive"] }
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.30.2"
comfy-table = "8.0.0"
hickory-resolver = "0.26.1"
futures = "0.3.34"
netsock = { version = "0.8.0", features = ["serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
home = "0.5.12"
termtree = "1.0.0"

[target.'cfg(windows)'.dependencies]
winreg = "0.56.0"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
