[package]
name = "ntap"
version = "0.9.0"
edition = "2021"
authors = ["shellrow <shellrow@foctal.com>"]
description = "Network traffic monitor/analyzer"
repository = "https://github.com/shellrow/ntap"
homepage = "https://github.com/shellrow/ntap"
documentation = "https://github.com/shellrow/ntap"
readme = "README.md"
keywords = ["network","security","cross-platform"]
categories = ["network-programming"]
license = "MIT"

[dependencies]
anyhow = { version = "1" }
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["time", "chrono"] }
netdev = { version = "0.38", features = ["serde"] }
nex = { version = "0.23", features = ["serde"] }
tokio = { version = "1" }
clap = { version = "4.5", features = ["cargo"] }
crossterm = "0.27"
rand = "0.8"
ratatui = "0.25"
comfy-table = "7.1"
hickory-resolver = { version = "0.24" }
futures = {version = "0.3"}
netsock = { version = "0.3", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
ipnet = { version = "2.11" }
home = "0.5"
termtree = "0.5"
indicatif = { version = "0.18" }
inquire = "0.6"
ndb-tcp-service = { version = "0.3", features = ["bundled"] }
ndb-udp-service = { version = "0.3", features = ["bundled"] }
ndb-as = { version = "0.3", features = ["bundled"] }
ndb-ipv4-asn = { version = "0.3", features = ["bundled"] }
ndb-ipv6-asn = { version = "0.3", features = ["bundled"] }
ndb-ipv4-country = { version = "0.3", features = ["bundled"] }
ndb-ipv6-country = { version = "0.3", features = ["bundled"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.50"

#[features]
#default = ["bundled"]
#bundled = [
#    "ndb-oui/bundled",
#    "ndb-tcp-service/bundled",
#    "ndb-udp-service/bundled",
#    "ndb-as/bundled",
#    "ndb-ipv4-asn/bundled",
#    "ndb-ipv6-asn/bundled",
#    "ndb-ipv4-country/bundled",
#    "ndb-ipv6-country/bundled",
#]

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
