[workspace]
resolver = "2"
members = [
    "ntap-core",
    "ntap", 
    "ntap-desktop/src-tauri",
    "db/ntap-db-ipv4-asn", 
    "db/ntap-db-ipv4-country", 
    "db/ntap-db-ipv6-asn", 
    "db/ntap-db-ipv6-country", 
    "db/ntap-db-as", 
    "db/ntap-db-country", 
    "db/ntap-db-tcp-service", 
    "db/ntap-db-udp-service", 
    "db/ntap-db-oui",
]
default-members = [
    "ntap-core",
    "ntap", 
    "db/ntap-db-ipv4-asn", 
    "db/ntap-db-ipv4-country", 
    "db/ntap-db-ipv6-asn", 
    "db/ntap-db-ipv6-country", 
    "db/ntap-db-as", 
    "db/ntap-db-country", 
    "db/ntap-db-tcp-service", 
    "db/ntap-db-udp-service", 
    "db/ntap-db-oui",
]

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.15.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
#installers = ["shell", "powershell", "homebrew"]
installers = ["shell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "shellrow/homebrew-tap-ntap"
# Target platforms to build apps for (Rust target-triple syntax)
#targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
